# config/cloudinary.yml
development: 
  cloud_name: "ds4ryxijh"
  api_key: "798791972666396"
  api_secret: "a5w0E-h07XAT-eX7_qsQPlCJ7DA"
  secure: true

production:
  cloud_name: "ds4ryxijh"
  api_key: "798791972666396"
  api_secret: "a5w0E-h07XAT-eX7_qsQPlCJ7DA"
  secure: true