development:
  secret_key_base: "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"
  google_client_id: "529886217365-7uu4c5j5605cqeskvkem8jeburhqgspk.apps.googleusercontent.com"
  google_client_secret: "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"